import './globals.css'
import {Inter} from 'next/font/google';
import {ReactNode} from "react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
    variable: '--font-base',
    subsets: ['latin'],
    display: 'swap'
});

export default function RootLayout({ children }: {
  children: ReactNode;
}) {
  return (
      <html lang="en" className={inter.variable}>
        <body>{children}</body>
      </html>
  );
}